site_name: Notatki z Matematyki

theme:
  name: material

nav:
  - Головна: index.md
  - Похідні: pochodne.md

markdown_extensions:
  - pymdownx.arithmatex

extra_javascript:
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
